### ISSUE TITLE
Including paths symlinked to node_modules

### ISSUE THREAD

**Issue by raine** [6to5/6to5ify#12]
`node_modules` is ignored by default it seems.

Assuming I have symlinked my `lib` directory to `node_modules`, is there a way to still run that path through 6to5-browserify?

Also open to other suggestion on how to avoid `require('../../../lib/stuff')` than with symlinks to `node_modules`.

**Comment by davidtheclark** [comment]
As @sebmck suspected, this is default Browserify behavior:

**Comment by davidtheclark** [comment]
@raine's second question, about long relative paths, is also a Browserify issue, not 6to5. You can use the ["browser" field](https://github.com/substack/node-browserify#browser-field) to a point; or you can use symlinks; or you can try [remapify](https://github.com/joeybaker/remapify) or something similar.

**Comment by sebmck** [comment]
@davidtheclark Great, thanks for looking into this!
