### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by bahlo** [6to5/6to5ify#22]
Hello,

I'm using 6to5ify with Browserify to get modules working properly with the following task:
```js
gulp.task('scripts', function() {
  return gulp.src("js/main.js")
    .pipe(browserify({
        transform: [to5ify]
    }))
    .pipe(gulp.dest('./dist'));
});
```

This works just fine, but it throws the error `ReferenceError: Can't find variable: Symbol`, caused by this conversion:
```js
for (let myObject of myArray) {
  // ...
}
```
becomes:
```js
for (var _iterator = myArray[Symbol.iterator](), _step; !(_step = _iterator.next()).done;) {
  var object = _step.value;
  // ...
}
```

Symbol is defined nowhere. Should I just avoid using the `for-of`-loop?

Greetings
Arne Bahlo

**Comment by sebmck** [comment]
See the [FAQ](http://6to5.org/docs/faq/#why-are-there-array-from-and-symbol-in-my-code-these-don-t-exist-) for reasoning. Also see the [caveats](http://6to5.org/docs/caveats/) for the certain 6to5 features that use ES6 methods such as `Symbol` and `Array.from`.

**Comment by bahlo** [comment]
Ah, I see. Thank you very much.

**Comment by JoshCheek** [comment]
@kittens neither of the links resolve for me. I was able to get a page by swapping "6to5.org" with "babeljs.io" (https://babeljs.io/docs/faq/) but it is very sparse so its unclear what is wrong and what to do about it.

**Comment by loganfsmyth** [comment]
@JoshCheek You'll need to load `babel-polyfill` in your application. Please refer to our README for more support channels: https://github.com/babel/babel#looking-for-support

**Comment by WojtekKruszewski** [comment]
> Since Babel only transforms syntax (like arrow functions), you can use babel-polyfill in order to support new globals such as Promise or new native methods like String.padStart (left-pad). It uses core-js and regenerator. Check out our babel-polyfill docs for more info.

From http://babeljs.io/#polyfill

**Comment by thanatos** [comment]
> Since Babel only transforms syntax 

This is misleading, IMO; from the POV of the user, all I'm doing is a syntax transformation (`for of`). Yet I end up requiring babel-polyfill anyways.

**Comment by rdking** [comment]
There's a bigger question here. Why does the 6->5 translation of the ES6 for..of syntax into ES5 syntax include the ES6 feature Symbol? That makes no sense.
