### ISSUE TITLE
Junk written to stdout

### ISSUE THREAD

**Issue by atombender** [6to5/6to5ify#25]
Something is emitting an AST to stdout. For some reason it only happens in production (and it's breaking our deployment script, which uses stdout to pipe Browserify's output through the Google Closure compiler). Any idea what this could be? This is after a clean `npm install`.

```
./node_modules/.bin/browserify -t 6to5ify --extension .jsx app/bundles/app.js --outfile /dev/null
{ type: 'XJSOpeningElement',
  start: 1707,
  end: 1732,
  loc: 
   { start: { line: 61, column: 6 },
     end: { line: 61, column: 31 } },
  range: [ 1707, 1732 ],
  attributes: 
   [ { type: 'Property',
       kind: 'init',
       key: [Object],
       value: [Object],
       computed: undefined,
       loc: [Object],
       end: 1731,
       range: [Object],
       start: 1716,
       leadingComments: [],
       trailingComments: [] } ],
  name: 
   { type: 'Identifier',
     start: 1708,
     end: 1715,
     loc: { start: [Object], end: [Object] },
     range: [ 1708, 1715 ],
     name: 'section' },
  selfClosing: false }
[... lots more output ...]
```

Our shrinkwrap file, in case it helps: https://gist.github.com/atombender/2c1d523bc362324d3b7d.

**Comment by clavery** [comment]
Looks like this is caused by the 6to5/6to5 lib itself. I've opened a pull request to remove the log (6to5/6to5#469)

**Comment by atombender** [comment]
Looks like it. Thanks, reverting to an earlier version in the meantime.

**Comment by sebmck** [comment]
Ugh, sorry!
