### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by qubyte** [6to5/6to5ify#28]
I'm using 6to5ify with `{experimental: true}` passed to the configure method. Here's a script I'm using to create a bundle:

```javascript
var browserify = require('browserify');
var to5ify = require('6to5ify');
var brfs = require('brfs');
var fs = require('fs');
var path = require('path');
var uglifyify = require('uglifyify');

var devPath = path.join(__dirname, 'frontend', 'scripts', 'main.js');

browserify()
    .transform(to5ify.configure({experimental: true}))
    .transform(brfs)
    .transform({global: true}, uglifyify)
    .require(devPath, {entry: true})
    .bundle()
    .pipe(fs.createWriteStream(path.join(__dirname, 'build', 'bundle.js')));
```

When using the bundle, I get the aforementioned error. Is this an issue with the experimental flag?

**Comment by sebmck** [comment]
As documented in the [caveats](http://6to5.org/docs/caveats/), generators use require the [6to5 polyfill](http://6to5.org/docs/usage/polyfill/) or the [regenerator runtime](https://github.com/facebook/regenerator/blob/master/runtime.js).

**Comment by qubyte** [comment]
My apologies, and thanks for the quick response. I didn't spot that tab.

**Comment by tusharmath** [comment]
Generators a supported by default by chrome. It still doesn't work.

**Comment by trusktr** [comment]
@tusharmath That's because if you compile it to ES5 it's not using the browser's native features, so it depends on the regenerator library for the ES5 code to work. Bable [isn't planning to support feature detection](https://github.com/babel/babel/issues/2900).

**Comment by trusktr** [comment]
@sebmck What's your recommended way of making the regenerator runtime available?

**Comment by sebmck** [comment]
https://github.com/babel/babel#looking-for-support

**Comment by trusktr** [comment]
@sebmck It's hard to keep track of discussion on Slack, and SO has too much other stuff. Have you considered Discourse (discourse.org)?

**Comment by jmm** [comment]
@trusktr Not much has been done with it yet, and there may be some issues with sign up, but there's https://discuss.babeljs.io/.

**Comment by trusktr** [comment]
@jmm That looks great!! Any plans to put that on the front page?

**Comment by jmm** [comment]
@trusktr Yeah, I, or whomever, just has to do it sometime. https://github.com/babel/babel.github.io/issues/535

**Comment by adamkdean** [comment]
I'm also getting issues using `require("babel-core/register")` with `co`. 

    Trace: ReferenceError: regeneratorRuntime is not defined

I'm not running this in the browser, but I want JSX support via babel without having to transpile beforehand. Any ideas?

**Comment by xpepermint** [comment]
+1, works when using `babel-node` but not when converting the code with `babel src --out-dir dist`.

**Comment by adamkdean** [comment]
Thanks, I decided to solve it another way but I'll keep this in mind in case I run into this again.

**Comment by SerkanSipahi** [comment]
@xpepermint `babel-plugin-transform-runtime` works fine for me !

**Comment by jonesnc** [comment]
Installing `babel-plugin-transform-runtime` fixed this issue for me as well.

Shouldn't this be added to the `transform-regenerator` [plugin docs](http://babeljs.io/docs/plugins/transform-regenerator/) as a dependency?

**Comment by jonesnc** [comment]
I also had to install `babel-polyfill` and include `require('babel-polyfill')` at the top of my source file to fix this issue.

**Comment by wangxiao** [comment]
`babel-plugin-transform-runtime` not works.
have an error
```
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/promise'
```
@SerkanSipahi @xpepermint 

```
    module: {
      loaders: [
        {
          test: /\.js$/,
          exclude: /node_modules/,
          loader: "babel-loader",
          query: {
            presets: ['es2015', 'stage-3'],
            plugins: ['transform-runtime']
          }
        }
      ]
    },
```

**Comment by jonesnc** [comment]
Do you have the `babel-runtime` module installed?

**Comment by wangxiao** [comment]
@jonesnc thanks, but after install `babel-runtime`, have a new error in browser.

```
Uncaught TypeError: (0 , _typeof3.default) is not a function
```

😂

**Comment by gscottolson** [comment]
I am seeing a similar error in the browser: `Uncaught TypeError: (0 , _typeof3.default) is not a function`

**Comment by adictovirtual** [comment]
same here !!

**Comment by mkozjak** [comment]
same here :)

**Comment by zertosh** [comment]
"Same here" without any info, makes it impossible to figure out what's going on. Please open a new issue with details like (1) what's the exact transform you're running? (2) what versions of babel & friends (3) what code you're running it on. Preferably with a repro case.
