### ISSUE TITLE
3.0.0 throws ReferenceError

### ISSUE THREAD

**Issue by davidtheclark** [6to5/6to5ify#29]
Just tried to upgrade, and I'm hitting this error: `ReferenceError: Unknown option: _flags while parsing file: ...`

Must be connected to browserify's `_flags` mentioned at the bottom of this section: https://github.com/substack/node-browserify#btransformtr-opts ???

**Comment by sebmck** [comment]
@davidtheclark Grrr, looks like I'll have to add in a check to ignore underscore options. Thanks!

**Comment by sebmck** [comment]
Fixed as of 6to5 3.0.3, thanks! 6to5ify will automatically get the latest 6to5 version so you'll have to force reinstall it.

**Comment by davidtheclark** [comment]
You got it! Thanks for the quick response.
