### ISSUE TITLE
Unexpected token on object spread

### ISSUE THREAD

**Issue by dshook** [6to5/6to5ify#32]
Apologies if this is for the wrong project since I haven't been able to do a direct 6to5 transform on the command line but this works in the 6to5 REPL.

In test.js:
```
var props = {a: 1, b: 2, c: 3};
var {a, ...other} = props;

```
I get the error 

test.js:2
var { a, ...other } = props;
         ^
ParseError: Unexpected token

Using the command 
 browserify .\test.js -t [6to5ify --experimental --playground --whitelist es7.objectSpread] --outfile bundle.js

I've tried various combinations of the experimental, playground, and whitelist settings but to no avail.

Am I missing something?

**Comment by sebmck** [comment]
The ES7 Object Destructuring is actually just done in the `es6.destructuring` transformer. It should really be split up but the current architecture makes it easy to have all the destructuring in one place. So to fix this you have two options:

 - Add the `es6.destructuring` transformer to your whitelist.
 - Remove your whitelist all together.

Let me know if you run into any additional problems, thanks!

**Comment by criso** [comment]
Hi, I'm running into the same issue.
Currently using:
browserify: 9.0.8
babelify: 6.0.2
```
%browserify -d -e ContentBlock.js -t babelify
SyntaxError: /Users/criso/ContentBlock.js: Unexpected token (5:33)
  3 | var ContentBlock = React.createClass({
  4 |   render: function() {
> 5 |     var { title, subtitle, menu, ...other } = this.props;
at Parser.pp.raise (/Users/criso/Dev/node_modules/babelify/node_modules/babel-core/lib/acorn/src/location.js:68:13)
    at Parser.pp.unexpected (/Users/criso/Dev/node_modules/babelify/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseIdent (/Users/criso/Dev/node_modules/babelify/node_modules/babel-core/lib/acorn/src/expression.js:731:10)
 ...
```

Only works if I do: browserify -d -e ContentBlock.js -t [ babelify --stage 0 ]
But I would prefer not to enable `stage 0`
Is that the new "way" of doing this?

**Comment by criso** [comment]
Hi, I'm running into the same issue.
Currently using:
browserify: 9.0.8
babelify: 6.0.2
```
%browserify -d -e ContentBlock.js -t babelify
SyntaxError: /Users/criso/ContentBlock.js: Unexpected token (5:33)
  3 | var ContentBlock = React.createClass({
  4 |   render: function() {
> 5 |     var { title, subtitle, menu, ...other } = this.props;
at Parser.pp.raise (/Users/criso/Dev/node_modules/babelify/node_modules/babel-core/lib/acorn/src/location.js:68:13)
    at Parser.pp.unexpected (/Users/criso/Dev/node_modules/babelify/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseIdent (/Users/criso/Dev/node_modules/babelify/node_modules/babel-core/lib/acorn/src/expression.js:731:10)
 ...
```

Only works if I do: browserify -d -e ContentBlock.js -t [ babelify --stage 0 ]
But I would prefer not to enable `stage 0`
Is that the new "way" of doing this?

**Comment by sebmck** [comment]
@criso Object spread/rest is a stage 2 feature so you can just use: `$ browserify -d -e ContentBlock.js -t [ babelify --stage 2 ]`. Alternatively you can use: `$ browserify -d -e ContentBlock.js -t [ babelify --optional es7.objectRestSpread ]`.

**Comment by criso** [comment]
fantastic - thanks!

**Comment by oguzbilgic** [comment]
@sebmck I'm running into the same issue too.

https://babeljs.io/docs/advanced/transformers/ Looking at this, is It still considered stage 2?

**Comment by worldsayshi** [comment]
I thinnk what @oguzbilgic was refering to is this: http://babeljs.io/docs/usage/options/

Adding stage 2 solved similar/same problem for me. These links may be useful to others walking this path:
https://babeljs.io/docs/plugins/
http://babeljs.io/docs/plugins/preset-stage-2/

**Comment by worldsayshi** [comment]
In case of useful, here's a snippet from my build script:
```
var b = browserify({
  cache: {},
  packageCache: {},
  plugin: [watchify],
  entries: ["./js/index.js"],
  debug: true
}).transform("babelify", {
    presets: ["es2015", "react", "stage-2"]
  }).on('update', bundle)
    .on('log', log);
```

**Comment by jwdomingo** [comment]
I installed Babel's stage-0 package and added **`stage-0`** as a preset in my **`.babelrc`** and was able to destructure in my Mocha/Chai tests.

My test script is:
```
"test": "mocha --compilers js:babel-register --recursive"
```
