### ISSUE TITLE
Constructors don't inherit properly.

### ISSUE THREAD

**Issue by radiosilence** [6to5/6to5ify#34]
Paste this into the REPL.

    class A {
      constructor(name) {
        this._name = name;
      }
      sayHi() {
        console.log(`Hi, I'm ${this._name}`);
      }
    }
    
    class B extends A {}
    
    var a = new A("foo");
    a.sayHi();
    
    var b = new B("foo");
    b.sayHi();

Expected output:

    Hi, I'm foo
    Hi, I'm bar

Output:

    Hi, I'm foo
    Hi, I'm [object Object]

**Comment by thejameskyle** [comment]
Moving to the main repo: https://github.com/6to5/6to5/issues/684
