### ISSUE TITLE
'global is not defined' with require("6to5ify/polyfill");

### ISSUE THREAD

**Issue by subblue** [6to5/6to5ify#36]
I want to include the 6to5 polyfill to get support for Promises in older browsers but including the ```require("6to5ify/polyfill");``` at the top of my main entry file for browserify I get the `global not defined` error. I'm using browserify with gulp but the task is pretty much the same as the node example in the 6to5ify readme.
What is the correct way to enable the pollyfills when using 6to5ify?

Thanks!

**Comment by sebmck** [comment]
Browserify should shim in `global` and make it available in browser environments. Not sure why this would be happening but you could alternatively just:

```sh
$ npm install 6to5 --save
```

```javascript
require("6to5/polyfill");
```

Which *should* work.

**Comment by subblue** [comment]
Sorry Sebastian, I just noticed I had ```detectGlobals: false``` still in my browserify options. 
Setting this back to the default ```true``` state sorted it out :)
Thanks!

**Comment by sebmck** [comment]
Great! No problem, more than happy to help :stuck_out_tongue_winking_eye:
