### ISSUE TITLE
this is undefined for React components

### ISSUE THREAD

**Issue by oncletom** [6to5/6to5ify#37]
I have a jsx file which is roughly the following:

```js
let React = require('react');

module.exports = React.createClass({
  getInitialState: () => { username: 'John Doe' },

  render: () => {
    return (<div>{this.state.username}</div>);
  }
});
```

When I browserify my code, the outcome is:

```js
var React = require('react');

module.exports = React.createClass({
  getInitialState: function() {
    return { username: 'John Doe' };
  },

  render: function() {
    return React.createElement('div', null, undefined.state.username);
  }
});
```

Notice the `undefined.state.username` bit. Any idea where it comes from?

Thanks :-)

**Comment by sebmck** [comment]
See 6to5/6to5#733. Arrow functions aren't equivalent to normal functions, whenever you use `this` inside them it refers to the outer `this`.

**Comment by oncletom** [comment]
OK I see thanks! I suppose this would have worked if I used the `Component extends React.Component` and the new method definition (aka `render(){ ... }`. Thanks :-)

**Comment by sebmck** [comment]
You can also use the method shorthand syntax inside object literals like so:

```
let React = require('react');

module.exports = React.createClass({
  getInitialState() { return username: 'John Doe'; },

  render() {
    return (<div>{this.state.username}</div>);
  }
});
```

**Comment by oncletom** [comment]
:+1: ah that's great thanks! I did not know it worked for non-class declarations. Thanks :-)

**Comment by sebmck** [comment]
No problem! Happy to answer any questions, feel free to check out our [gitter room](https://gitter.im/6to5/6to5) too.

**Comment by IngwiePhoenix** [comment]
Sorry for butting in all of a sudden :)

I just began using Babel alltogether and realized, that sometimes this:

```javascript
(function(){
    // ...
}).call(this);
```

Would become this:

```javascript
(function(){
    // ...
}).call(undefined);
```

instead. Namely, the undefined-treatment happens against this line: https://github.com/musictheory/oj/blob/master/src/runtime.js#L375

What is the best way to get rid of that behaviour, altogether?

**Comment by zertosh** [comment]
@IngwiePhoenix That's being done by [babel-plugin-transform-es2015-modules-commonjs](babel-plugin-transform-es2015-modules-commonjs). It's part of [babel-preset-es2015](http://babeljs.io/docs/plugins/preset-es2015/). You can turn off transforming the top level `this` to `undefined` by passing it [`{allowTopLevelThis: true}`](https://github.com/babel/babel/blob/v6.2.2/packages/babel-plugin-transform-es2015-modules-commonjs/src/index.js#L127). Like this:

```js
plugins: [
  [require('babel-plugin-transform-es2015-modules-commonjs'), {allowTopLevelThis: true}]
]
```

That of course means that you can't use a preset, you'll have to specify the transforms individually so you can pass in that option.

**Comment by IngwiePhoenix** [comment]
Really? How come this won't work with a preset?

2015-11-27 5:30 GMT+01:00 Andres Suarez <notifications@github.com>:

**Comment by zertosh** [comment]
Presets don't take options.

**Comment by brendensoares** [comment]
So the workaround to get `this` scoped to the parent scope is the old `var that = this`? That's a shame. Also a shame you can't pass in options with the Babel preset :(

**Comment by loganfsmyth** [comment]
@brendensoares It's not clear what you're asking. I'd recommend dropping by [our documented support channels](https://github.com/babel/babel#looking-for-support) or `#javascript` on Freenode if you have specific ES6 questions.
