### ISSUE TITLE
transform not applying to files required through symlinked path

### ISSUE THREAD

**Issue by codekirei** [6to5/6to5ify#38]
[repo example](https://github.com/codekirei/browserify-6to5-bug-example)

I like to symlink my local `app` directory (or `lib`, or wherever my `js` lives) inside `node_modules` to prevent the need for relative path soup when requiring local modules.

Substack talks about this [here](https://github.com/substack/browserify-handbook#organizing-modules).

I've discovered that when using the 6to5ify transform with requires that follow a symlinked path, the required modules do not get transformed.

Haven't poked this too hard, so not sure if it's an issue with browserify, 6to5, or 6to5ify (or [pebkac](https://en.wikipedia.org/wiki/User_error#Acronyms_and_other_names)).

To reproduce from example repo:

1. `npm i`
2. `npm run build`

Compare the bundles. ES6 features persist in `bundle_sym.js`, specifically in the file that was required through the symlink.

**Comment by sebmck** [comment]
This is the behaviour of browserify, 6to5ify has nothing to do with it. Adding `6to5ify` to the `browserify` object in your `package.json` of the symlinked folder *should* work:

**package.json**

```javascript
{
  ...
  "browserify": {
    "transform": [
      "6to5ify"
    ]
  }
}
```

**Comment by codekirei** [comment]
Brilliant, that works! Much thanks for figuring this out (and responding so quickly!) even though the issue is browserify-specific. 

I've updated my [example repo](https://github.com/codekirei/browserify-6to5-bug-example) with the solution, credited you, and linked to this issue.
