### ISSUE TITLE
Runtime option

### ISSUE THREAD

**Issue by ooflorent** [6to5/6to5ify#41]
Currently the `runtime` option does not add `runtime.js` to the browserified bundle. The runtime is neither accessible through `require('6to5ify').runtime` or `require('6to5ify/runtime')`. 

What is the best practice to include the runtime into the bundle?

**Comment by sebmck** [comment]
It's not supposed to add it to the browserified bundle, there's no way to attach files to the current browserify stream.

Sounds like what you're looking for is the [optional selfContained transformer](6to5.org/docs/usage/transformers/#self-contained). Just add the `6to5-runtime` to your `package.json` and use add the `{ optional: ["selfContained"] }` option.

**Comment by ooflorent** [comment]
Hmm. I must do something wrong:

```js
gulp.task('js', function() {
  var b = browserify('./src/index.js', {
    standalone: 'admin',
    debug: true,
    cache: {},
    packageCache: {},
  })

  b.transform(to5.configure({
    runtime: true,
    optional: ['selfContained']
  }))

  return b.bundle()
    .pipe(source('main.js'))
    .pipe(gulp.dest('dist'))
})
```

`dist/main.js` does not contain the runtime.
I tried add the runtime to build process but it does not work as expected:

```js
b.require('6to5-runtime/helpers')
```

But `to5Runtime` is still not included:

```js
// Extract from `main.js`
function(require, module, exports) {
  "use strict";

  var Test = exports.Test = function Test() {
    to5Runtime.classCallCheck(this, Test);
  };

  Object.defineProperty(exports, "__esModule", {
    value: true
  });
}
```

**Comment by sebmck** [comment]
You aren't meant to use the `runtime` and `selfContained` transformer together since they're fundamentally different. You'd just use the following options:

```javascript
b.transform(to5.configure({
  optional: ['selfContained']
}))
```

**Comment by ooflorent** [comment]
Oh crap... Thanks a lot!

**Comment by sebmck** [comment]
No problem! Let me know if you run into anymore issues.
